/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "box_call.h"

// int *
char **
call_blackbox_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static char * result;
	// static int result;

	printf("File: %s\n", argp->blackbox);
	printf("Input1: %d\n", argp->first);
	printf("Input2: %d\n", argp->second);

	result = "This is done\nAnd this is yes done\n";
	// result = 2;
	return &result;
}
