// The project aims to execute three programs and communicate between them.
// The server and blackbox programs communicate through pipes while the server 
// and client applications communicate with RPC protocol.
//
// An example client application is generated with rpcgen. 
// In this source code, the main function and server call functions are
// edited according to project needs. The RPC call happens in the box_call_clnt.c file
// which is generated by rpcgen. Client program takes two inputs from user,
// sends them to the server via RPC, takes back the result string from server
// and writes the result string to output file.
//
// @author: Mehmet Akın Elden

#include <stdio.h>
#include "box_call.h"

// this function calls the server with given parameters and returns the result string
//	server: The address of the server application
//	blackbox: The path of the blackbox application
//	first: The first integer parameter
//	second: The second integer parameter
//	returns: The result string of the blackbox operation
char *call_server(char *server, char *blackbox, int first, int second)
{
	// the rpc client
	CLIENT *client;
	// the input arguments stored in a struct
	inputs arguments = {blackbox, first, second};

#ifndef DEBUG
	client = clnt_create(server, BLACKBOX_CALL, CALL_VERSION, "udp");
	if (client == NULL)
		exit(-1);
#endif /* DEBUG */

	char **result = call_blackbox_1(&arguments, client);
	if (result == (char **)NULL)
		exit(-1);

#ifndef DEBUG
	clnt_destroy(client);
#endif /* DEBUG */
	return *result;
}

// In the main function, two integer inputs are taken from the user
// and the call_server function is executed with the inputs.
// The result of the call is written to output file.
int main(int argc, char *argv[])
{

	if (argc < 4)
	{
		printf("blackbox, outputfile and host arguments are required.");
		return -1;
	}
	// path of blackbox
	char *blackbox = argv[1];
	// path of output file
	char *outputPath = argv[2];
	// address of server
	char *server = argv[3];

	// input integers
	int first, second;
	// read input from console
	scanf("%d", &first);
	scanf("%d", &second);

	// call server with the input parameters
	char* result = call_server(server, blackbox, first, second);

	// open the output file and write content to it
	FILE *fp = fopen(outputPath, "a");
	fprintf(fp, "%s", result);
	fclose(fp);

	return 0;
}
